import { create } from 'zustand'

export interface MusicTrack {
  id: string
  title: string
  artist: string
  source: 'local' | 'url' | 'generator'
  /** 本地文件路径 / 网络 URL / 生成器类型标识 */
  src: string
  duration?: number
  genre?: string
  license?: string
}

interface MusicState {
  playlist: MusicTrack[]
  currentIndex: number

  isPlaying: boolean
  volume: number
  currentTime: number
  duration: number

  isExpanded: boolean
  showMiniPlayer: boolean

  setPlaylist: (tracks: MusicTrack[]) => void
  addTrack: (track: MusicTrack) => void
  removeTrack: (id: string) => void
  playTrack: (index: number) => void
  nextTrack: () => void
  prevTrack: () => void
  togglePlay: () => void
  setVolume: (v: number) => void
  setCurrentTime: (t: number) => void
  setDuration: (d: number) => void
  setExpanded: (e: boolean) => void
  setShowMiniPlayer: (s: boolean) => void

  currentTrack: () => MusicTrack | null
}

// Built-in ambient sound generators (Web Audio API, 100% copyright-free, works offline)
const BUILTIN_GENERATORS: MusicTrack[] = [
  {
    id: 'builtin-white-noise',
    title: 'White Noise',
    artist: 'Scroll Generator',
    source: 'generator',
    src: 'generator:whitenoise',
    genre: 'ambient',
    license: 'Generated by Scroll — 100% copyright-free'
  },
  {
    id: 'builtin-brown-noise',
    title: 'Brown Noise',
    artist: 'Scroll Generator',
    source: 'generator',
    src: 'generator:brownnoise',
    genre: 'ambient',
    license: 'Generated by Scroll — 100% copyright-free'
  },
  {
    id: 'builtin-soft-pad',
    title: 'Soft Pad',
    artist: 'Scroll Generator',
    source: 'generator',
    src: 'generator:softpad',
    genre: 'ambient',
    license: 'Generated by Scroll — 100% copyright-free'
  },
  {
    id: 'builtin-rain',
    title: 'Rain Sounds',
    artist: 'Scroll Generator',
    source: 'generator',
    src: 'generator:rain',
    genre: 'nature',
    license: 'Generated by Scroll — 100% copyright-free'
  }
]

export const useMusicStore = create<MusicState>((set, get) => ({
  playlist: [...BUILTIN_GENERATORS],
  currentIndex: -1,

  isPlaying: false,
  volume: 0.5,
  currentTime: 0,
  duration: 0,

  isExpanded: false,
  showMiniPlayer: false,

  setPlaylist: (tracks) => set({ playlist: tracks }),

  addTrack: (track) =>
    set((s) => {
      if (s.playlist.find((t) => t.src === track.src)) return s
      return { playlist: [...s.playlist, track] }
    }),

  removeTrack: (id) =>
    set((s) => {
      const idx = s.playlist.findIndex((t) => t.id === id)
      const newList = s.playlist.filter((t) => t.id !== id)
      let newIdx = s.currentIndex
      if (idx === s.currentIndex) {
        newIdx = newList.length > 0 ? Math.min(idx, newList.length - 1) : -1
      } else if (idx < s.currentIndex) {
        newIdx = s.currentIndex - 1
      }
      return { playlist: newList, currentIndex: newIdx }
    }),

  playTrack: (index) =>
    set({
      currentIndex: index,
      isPlaying: true,
      currentTime: 0,
      showMiniPlayer: true
    }),

  nextTrack: () =>
    set((s) => {
      if (s.playlist.length === 0) return s
      const next = (s.currentIndex + 1) % s.playlist.length
      return { currentIndex: next, isPlaying: true, currentTime: 0 }
    }),

  prevTrack: () =>
    set((s) => {
      if (s.playlist.length === 0) return s
      const prev = s.currentIndex <= 0 ? s.playlist.length - 1 : s.currentIndex - 1
      return { currentIndex: prev, isPlaying: true, currentTime: 0 }
    }),

  togglePlay: () => set((s) => ({ isPlaying: !s.isPlaying })),

  setVolume: (v) => set({ volume: v }),
  setCurrentTime: (t) => set({ currentTime: t }),
  setDuration: (d) => set({ duration: d }),
  setExpanded: (e) => set({ isExpanded: e }),
  setShowMiniPlayer: (s) => set({ showMiniPlayer: s }),

  currentTrack: () => {
    const { playlist, currentIndex } = get()
    return playlist[currentIndex] || null
  }
}))
