import { create } from 'zustand'

export interface MusicTrack {
  id: string
  title: string
  artist: string
  source: 'local' | 'url' | 'generator'
  /** 本地文件路径 / 网络 URL / 生成器类型标识 */
  src: string
  duration?: number
  genre?: string
  license?: string
}

interface MusicState {
  playlist: MusicTrack[]
  currentIndex: number

  isPlaying: boolean
  volume: number
  currentTime: number
  duration: number

  isExpanded: boolean
  showMiniPlayer: boolean
  hydrated: boolean
  /** 本地文件路径不存在或无法播放 */
  unavailableTrackIds: string[]

  setPlaylist: (tracks: MusicTrack[]) => void
  addTrack: (track: MusicTrack) => boolean
  removeTrack: (id: string) => void
  playTrack: (index: number) => void
  nextTrack: () => void
  prevTrack: () => void
  togglePlay: () => void
  pause: () => void
  setVolume: (v: number) => void
  setCurrentTime: (t: number) => void
  setDuration: (d: number) => void
  setExpanded: (e: boolean) => void
  setShowMiniPlayer: (s: boolean) => void
  setHydrated: (h: boolean) => void
  setUnavailableTrackIds: (ids: string[]) => void
  markTrackUnavailable: (id: string) => void
  hydrate: (payload: {
    playlist: MusicTrack[]
    volume: number
    currentIndex: number
    showMiniPlayer: boolean
    unavailableTrackIds?: string[]
  }) => void

  currentTrack: () => MusicTrack | null
}

// Built-in ambient sound generators (Web Audio API, 100% copyright-free, works offline)
export const BUILTIN_GENERATORS: MusicTrack[] = [
  {
    id: 'builtin-white-noise',
    title: 'White Noise',
    artist: 'Scroll Generator',
    source: 'generator',
    src: 'generator:whitenoise',
    genre: 'ambient',
    license: 'Generated by Scroll — 100% copyright-free'
  },
  {
    id: 'builtin-brown-noise',
    title: 'Brown Noise',
    artist: 'Scroll Generator',
    source: 'generator',
    src: 'generator:brownnoise',
    genre: 'ambient',
    license: 'Generated by Scroll — 100% copyright-free'
  },
  {
    id: 'builtin-soft-pad',
    title: 'Soft Pad',
    artist: 'Scroll Generator',
    source: 'generator',
    src: 'generator:softpad',
    genre: 'ambient',
    license: 'Generated by Scroll — 100% copyright-free'
  },
  {
    id: 'builtin-rain',
    title: 'Rain Sounds',
    artist: 'Scroll Generator',
    source: 'generator',
    src: 'generator:rain',
    genre: 'nature',
    license: 'Generated by Scroll — 100% copyright-free'
  }
]

const BUILTIN_ID_SET = new Set(BUILTIN_GENERATORS.map((t) => t.id))

export function mergePlaylist(userTracks: MusicTrack[]): MusicTrack[] {
  const merged = [...BUILTIN_GENERATORS]
  const seenIds = new Set(BUILTIN_ID_SET)
  const seenSrc = new Set(BUILTIN_GENERATORS.map((t) => t.src))

  for (const track of userTracks) {
    if (track.source === 'generator') continue
    if (seenIds.has(track.id) || seenSrc.has(track.src)) continue
    merged.push(track)
    seenIds.add(track.id)
    seenSrc.add(track.src)
  }

  return merged
}

export const useMusicStore = create<MusicState>((set, get) => ({
  playlist: [...BUILTIN_GENERATORS],
  currentIndex: -1,

  isPlaying: false,
  volume: 0.5,
  currentTime: 0,
  duration: 0,

  isExpanded: false,
  showMiniPlayer: false,
  hydrated: false,
  unavailableTrackIds: [],

  setPlaylist: (tracks) => set({ playlist: tracks }),

  addTrack: (track) => {
    let added = false
    set((s) => {
      if (s.playlist.some((t) => t.id === track.id || t.src === track.src)) return s
      added = true
      return { playlist: [...s.playlist, track] }
    })
    return added
  },

  removeTrack: (id) =>
    set((s) => {
      const idx = s.playlist.findIndex((t) => t.id === id)
      const newList = s.playlist.filter((t) => t.id !== id)
      let newIdx = s.currentIndex
      if (idx === s.currentIndex) {
        newIdx = newList.length > 0 ? Math.min(idx, newList.length - 1) : -1
      } else if (idx < s.currentIndex) {
        newIdx = s.currentIndex - 1
      }
      return {
        playlist: newList,
        currentIndex: newIdx,
        unavailableTrackIds: s.unavailableTrackIds.filter((x) => x !== id)
      }
    }),

  playTrack: (index) =>
    set({
      currentIndex: index,
      isPlaying: true,
      currentTime: 0,
      showMiniPlayer: true
    }),

  nextTrack: () =>
    set((s) => {
      if (s.playlist.length === 0) return s
      const next = (s.currentIndex + 1) % s.playlist.length
      return { currentIndex: next, isPlaying: true, currentTime: 0 }
    }),

  prevTrack: () =>
    set((s) => {
      if (s.playlist.length === 0) return s
      const prev = s.currentIndex <= 0 ? s.playlist.length - 1 : s.currentIndex - 1
      return { currentIndex: prev, isPlaying: true, currentTime: 0 }
    }),

  togglePlay: () => set((s) => ({ isPlaying: !s.isPlaying })),

  pause: () => set((s) => (s.isPlaying ? { isPlaying: false } : s)),

  setVolume: (v) => set({ volume: v }),
  setCurrentTime: (t) => set({ currentTime: t }),
  setDuration: (d) => set({ duration: d }),
  setExpanded: (e) => set({ isExpanded: e }),
  setShowMiniPlayer: (s) => set({ showMiniPlayer: s }),
  setHydrated: (h) => set({ hydrated: h }),
  setUnavailableTrackIds: (ids) => set({ unavailableTrackIds: ids }),
  markTrackUnavailable: (id) =>
    set((s) => (s.unavailableTrackIds.includes(id) ? s : { unavailableTrackIds: [...s.unavailableTrackIds, id] })),

  hydrate: (payload) =>
    set({
      playlist: payload.playlist,
      volume: payload.volume,
      currentIndex: payload.currentIndex,
      showMiniPlayer: payload.showMiniPlayer,
      unavailableTrackIds: payload.unavailableTrackIds ?? [],
      hydrated: true
    }),

  currentTrack: () => {
    const { playlist, currentIndex } = get()
    return playlist[currentIndex] || null
  }
}))
